"""New migration

Revision ID: 0955e9a601b1
Revises: 9a745421015c
Create Date: 2023-07-03 12:46:30.243827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0955e9a601b1'
down_revision = '9a745421015c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
