"""New migration

Revision ID: 1608dff18b8b
Revises: 498f6c8d9b59
Create Date: 2023-07-03 18:17:03.919312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1608dff18b8b'
down_revision = '498f6c8d9b59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
