"""New migration

Revision ID: 1a9192d23834
Revises: f7949296ebbc
Create Date: 2023-07-03 18:30:40.246208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9192d23834'
down_revision = 'f7949296ebbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
