"""New migration

Revision ID: 25312c6a78f4
Revises: 7f7aa322ef8a
Create Date: 2023-07-03 18:14:01.912593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25312c6a78f4'
down_revision = '7f7aa322ef8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
