"""New migration

Revision ID: 2ceb820e46c3
Revises: 32ac3c81574f
Create Date: 2023-07-03 19:13:12.145536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ceb820e46c3'
down_revision = '32ac3c81574f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
