"""New migration

Revision ID: 498f6c8d9b59
Revises: ee232701609e
Create Date: 2023-07-03 18:14:45.072728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498f6c8d9b59'
down_revision = 'ee232701609e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
