"""New migration

Revision ID: 532b6d7e42a2
Revises: 58447959e981
Create Date: 2023-07-03 15:47:53.210908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532b6d7e42a2'
down_revision = '58447959e981'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
