"""New migration

Revision ID: 6174a894196b
Revises: 1a9192d23834
Create Date: 2023-07-03 18:30:51.624080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6174a894196b'
down_revision = '1a9192d23834'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
