"""New migration

Revision ID: 7f7aa322ef8a
Revises: 9f18a2625173
Create Date: 2023-07-03 18:12:29.538244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7aa322ef8a'
down_revision = '9f18a2625173'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
