"""New migration

Revision ID: 85f74e7f29ae
Revises: 1608dff18b8b
Create Date: 2023-07-03 18:18:04.001673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f74e7f29ae'
down_revision = '1608dff18b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
