"""New migration

Revision ID: 90de6d46f831
Revises: b13e9e83123a
Create Date: 2023-07-03 18:22:38.610294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90de6d46f831'
down_revision = 'b13e9e83123a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
