"""New migration

Revision ID: 951d19531542
Revises: 532b6d7e42a2
Create Date: 2023-07-03 15:48:20.766498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951d19531542'
down_revision = '532b6d7e42a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
