"""New migration

Revision ID: 98d44de15b5e
Revises: 2ceb820e46c3
Create Date: 2023-07-03 19:14:36.421611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d44de15b5e'
down_revision = '2ceb820e46c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
