"""New migration

Revision ID: 9ae32a43feec
Revises: 9e9a1bbaa9f7
Create Date: 2023-07-03 10:47:23.411128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae32a43feec'
down_revision = '9e9a1bbaa9f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
