"""New migration

Revision ID: 9e9a1bbaa9f7
Revises: a5f86ae12df7
Create Date: 2023-07-03 10:43:25.281340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9a1bbaa9f7'
down_revision = 'a5f86ae12df7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
