"""New migration

Revision ID: a5f86ae12df7
Revises: 1ebb8ea30199
Create Date: 2023-06-29 20:34:51.532408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f86ae12df7'
down_revision = '1ebb8ea30199'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
