"""New migration

Revision ID: b13e9e83123a
Revises: 85f74e7f29ae
Create Date: 2023-07-03 18:22:11.981623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13e9e83123a'
down_revision = '85f74e7f29ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
