"""New migration

Revision ID: b341dd6f3ac5
Revises: c647408aa3a0
Create Date: 2023-07-03 18:28:30.388010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b341dd6f3ac5'
down_revision = 'c647408aa3a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
