"""New migration

Revision ID: c275dc094534
Revises: 9ae32a43feec
Create Date: 2023-07-03 11:00:56.428272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c275dc094534'
down_revision = '9ae32a43feec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
