"""New migration

Revision ID: c647408aa3a0
Revises: 90de6d46f831
Create Date: 2023-07-03 18:28:19.881627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c647408aa3a0'
down_revision = '90de6d46f831'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
