"""New migration

Revision ID: d1191c3a787e
Revises: 6cd454afaa7a
Create Date: 2023-07-12 08:48:22.892050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1191c3a787e'
down_revision = '6cd454afaa7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
