"""New migration

Revision ID: eb55532a1c53
Revises: 14f4ea45b9f4
Create Date: 2023-06-29 19:45:24.754364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb55532a1c53'
down_revision = '14f4ea45b9f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
