"""New migration

Revision ID: f7949296ebbc
Revises: b341dd6f3ac5
Create Date: 2023-07-03 18:30:09.890948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7949296ebbc'
down_revision = 'b341dd6f3ac5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
